packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  "next": 15.1.0
  "react": 19.0.0
  "react-dom": 19.0.0
  "@types/node": ^22.10.2
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2
  "typescript": 5.7.2