packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  "next": ^15.0.0
  "react": ^19.0.0
  "react-dom": ^19.0.0
  "@types/node": ^22.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "typescript": ^5.0.0
  "@tailwindcss/postcss": ^4.0.0
  "tailwindcss": ^4.0.0
  "motion": ^11.0.0
  "date-fns": ^4.0.0
  "next-themes": "^0.4.4"
  "@vercel/analytics": "^1.5.0"
  "@vercel/speed-insights": "^1.2.0"
  "ky": "^1.7.5"
